name: marvel_comics
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  crypto: ^3.0.6
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.4.2
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
